### ISSUE TITLE
Investigate dependencies/blockers for feature

### ISSUE THREAD

**Issue by fpunny** [CSCD01/team_24-project#10]
## TODO
 - [x] Find other objects affected/need the changes (To ensure consistency, which is valued by Pandas)
 - [x] Informal plan how to implement changes

**Comment by fpunny** [comment]
- normalize_keyword_aggregation, how to extend that to ensure consistency and allowing for this feature
 - Allowing multi column for builtin functions like max, min. Perhaps we can just check for (list, lambda) only for now, and expand it as needed if possible

**Comment by mason-98** [comment]
- [ ] update existing d3 UMLs once we gain more knowledge of the problem
- [ ] add a UML diagram to better present our potential fix
