### ISSUE TITLE
Work on actual deliverable

### ISSUE THREAD

**Issue by fpunny** [CSCD01/team_24-project#4]
**Tasks**
 - [x] Examine issue list of project
 - [x] Write about issue 1
    - [x] Analyze issue
    - [x] Talk about what was done
    - [x] Discuss testing as needed
 - [x] Write about issue 2
    - [x] Analyze issue
    - [x] Talk about what was done
    - [x] Discuss testing as needed
 - [x] Write about about overall changes to project

**Comment by SpectrumWings** [comment]
General introduction and 5 issues listing completed
